### ISSUE TITLE
Add compilation script

### ISSUE THREAD

**Issue by tomlegkov** [tomlegkov/marine-core#11]
The script should compile Marine with `-j {CORE_COUNT-1}` and optionally put libmarine.so in a location supplied as a parameter by the user

**Comment by yehonatanz** [comment]
We already have those for CI and release on two different distributions (ubuntu + centos7).
So that issue is only relevant for a development script, but I don't really feel like that would be useful, since dev environments might be diverse, and the difficult know-how of the compilation process already resides the CI/release scripts.
